name = "swindon-blocked-drains"
type = "javascript"
main = "src/worker.ts"
workers_dev = false

[env.production]
routes = [
  { pattern = "swindonblockeddrains.co.uk/*", zone_id = "" }
]

[env.development]
vars = { ENVIRONMENT = "development" }
routes = [
  { pattern = "swindonblockeddrains.co.uk/*", zone_id = "" }
]

compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "swindon-blocked-drains-leads"
database_id = "4ce8f47b-6fe9-488d-8fb8-29f2ee61dc87"

[build]
command = "bun install && bun run build"
cwd = "./"
main = "dist/worker.js"

[build.upload]
format = "service-worker"
